CREATE TABLE IF NOT EXISTS users (id bigserial PRIMARY KEY, email varchar(255) NOT NULL UNIQUE, password_hash text NOT NULL, name varchar(100) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS account_categories (id bigserial PRIMARY KEY, name varchar(60) NOT NULL UNIQUE, color varchar(20));
CREATE TABLE IF NOT EXISTS accounts (id bigserial PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), platform varchar(120) NOT NULL, username varchar(255) NOT NULL, email varchar(255), category varchar(60) NOT NULL, registered_at timestamptz, password_strength varchar(20) NOT NULL, password_changed_at timestamptz, two_factor_enabled boolean NOT NULL DEFAULT false, known_breach boolean NOT NULL DEFAULT false, last_login_at timestamptz, notes text, status varchar(20) NOT NULL DEFAULT 'active', archived_at timestamptz, archive_reason varchar(255), password_hash varchar(255), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS subscriptions (id bigserial PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), account_id bigint, service_name varchar(120) NOT NULL, plan varchar(80), amount numeric(12,2) NOT NULL, currency varchar(10) NOT NULL DEFAULT 'CNY', cycle varchar(20) NOT NULL, status varchar(20) NOT NULL DEFAULT 'active', started_at timestamptz, next_billing_at timestamptz, cancelled_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS digital_footprints (id bigserial PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), account_id bigint, event_type varchar(40) NOT NULL, title varchar(160) NOT NULL, description text, event_at timestamptz NOT NULL, important boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS data_locations (id bigserial PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), account_id bigint, platform varchar(120) NOT NULL, data_type varchar(40) NOT NULL, size_gb numeric(12,2) NOT NULL, privacy varchar(20) NOT NULL, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS backup_records (id bigserial PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), account_id bigint, platform varchar(120) NOT NULL, cycle varchar(20) NOT NULL, last_backup_at timestamptz, next_backup_at timestamptz, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS notifications (id bigserial PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), type varchar(40) NOT NULL, title varchar(160) NOT NULL, message text NOT NULL, due_at timestamptz NOT NULL, channel varchar(20) NOT NULL DEFAULT 'console', status varchar(20) NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS security_events (id bigserial PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), account_id bigint NOT NULL REFERENCES accounts(id), type varchar(40) NOT NULL, detail text, event_at timestamptz NOT NULL);
